### ISSUE TITLE
能增加滚动加载新图片功能吗？

### ISSUE THREAD

**Issue by yuting816** [hugeorange/waterfalljs#2]
能不能直接监听滚动事件加载图片呢？谢谢！

**Comment by hugeorange** [comment]
- 看看下图这样操作能不能满足你的需求 @yuting816 
- 参考代码 https://codesandbox.io/s/busy-faraday-w538tc?file=/src/waterfall-grid.js
![image](https://user-images.githubusercontent.com/18440746/204074891-9c77b3a7-3328-4178-9b2c-e9f44a4cd58c.png)

**Comment by yuting816** [comment]
谢谢，我已经解决啦！我自己也写了一个简单的，可以看看~
